# Generated by Django 5.0.6 on 2024-06-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='local_user_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='user_type',
            field=models.CharField(choices=[('VECINO', 'Vecino'), ('RECOLECTOR', 'Recolector'), ('ADMIN', 'Admin')], default='standard', max_length=10),
        ),
    ]
