# Generated by Django 5.0.6 on 2024-06-25 14:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_personal', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('address_lat', models.FloatField(blank=True, null=True)),
                ('address_long', models.FloatField(blank=True, null=True)),
                ('additional_information', models.TextField(blank=True)),
                ('subscribed_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_type', models.CharField(choices=[('ACTIVIDAD_TIPO_USUARIO_VECINO', 'VECINO'), ('ACTIVIDAD_TIPO_USUARIO_RECOLECTOR', 'RECOLECTOR'), ('ACTIVIDAD_TIPO_USUARIO_ADMIN', 'ADMIN')], default='standard', max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('document_number', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
