# Generated by Django 5.0.6 on 2024-06-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_rename_profile_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='userId',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
