# Generated by Django 5.0.6 on 2024-06-25 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_perfil_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='userId',
            new_name='local_user_id',
        ),
    ]
