# Generated by Django 5.0.6 on 2024-08-16 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_profiles', '0003_rename_isactive_usersprofile_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('nit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
                ('nro_pregunta', models.IntegerField()),
                ('columna', models.CharField(max_length=1)),
                ('pregunta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prueba', models.DateField()),
                ('valor', models.IntegerField()),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='totem_temperamentos.organizacion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='totem_temperamentos.pregunta')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_profiles.usersprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Prueba_resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prueba_nro', models.IntegerField()),
                ('prioridad', models.CharField(max_length=50)),
                ('resultado', models.TextField()),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='totem_temperamentos.organizacion')),
            ],
        ),
    ]
