# Generated by Django 5.0.6 on 2024-08-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiopen', '0002_alter_answer_id_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='input_value',
            field=models.TextField(),
        ),
    ]
