# Generated by Django 5.0.6 on 2024-08-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiopen', '0003_alter_task_input_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='engine',
            field=models.CharField(default='GROQ', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='engine',
            field=models.CharField(default='GROQ', max_length=50),
        ),
    ]
