# Generated by Django 3.1.2 on 2024-05-31 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('casada', models.CharField(blank=True, max_length=255)),
                ('extension', models.CharField(max_length=255)),
                ('fechanac', models.DateTimeField(default=django.utils.timezone.now)),
                ('genero', models.CharField(max_length=255)),
                ('materno', models.CharField(max_length=255)),
                ('nomcompleto', models.CharField(max_length=255)),
                ('nombres', models.CharField(max_length=255)),
                ('nrodocumento', models.CharField(max_length=255)),
                ('nrodocumentochars', models.CharField(max_length=255)),
                ('nrodocumentoint', models.CharField(max_length=255)),
                ('paterno', models.CharField(max_length=255)),
                ('tipodocumento', models.CharField(max_length=255)),
            ],
        ),
    ]
